theme = "catppuccin_mocha"
client_port = 8080
enable_streaming = "Always"
enable_media_control = true
enable_notify = true
ap_port = 443

[device]
name = "Ghostty"
device_type = "speaker"
volume = 80
bitrate = 320
audio_cache = false
normalization = false
autoplay = true
