[mgr]
prepend_keymap = [
    # Навигация (h, j, k, l -> р, о, л, д)
    { on = [ "р" ], run = "leave",               desc = "Назад / Выйти из папки" },
    { on = [ "о" ], run = "arrow 1",             desc = "Курсор вниз" },
    { on = [ "л" ], run = "arrow -1",            desc = "Курсор вверх" },
    { on = [ "д" ], run = "enter",               desc = "Открыть / Войти в папку" },

    # Перемещение в начало и конец (gg, G -> пп, П)
    { on = [ "п", "п" ], run = "arrow top",      desc = "В начало списка" },
    { on = [ "П" ],       run = "arrow bot",      desc = "В конец списка" },

    # Действия с файлами
    { on = [ "я" ], run = "yank",                desc = "Копировать (yank)" },
    { on = [ "ч" ], run = "yank --cut",          desc = "Вырезать (cut)" },
    { on = [ "з" ], run = "paste",               desc = "Вставить (paste)" },
    { on = [ "в" ], run = "remove",               desc = "Удалить в корзину" },
    { on = [ "В" ], run = "remove --permanently",desc = "Удалить навсегда" },
    { on = [ "ф" ], run = "create",              desc = "Создать файл/папку" },
    { on = [ "к" ], run = "rename --cursor=before_ext", desc = "Переименовать" },

    # Меню Open with (Shift + щ = O) и выход (й = q)
    { on = [ "Щ" ], run = "open --interactive",  desc = "Open with..." },
    { on = [ "й" ], run = "quit",                desc = "Выход" },
]
